### ISSUE TITLE
Angular 1.6 - Possibly unhandled rejection: {}

### ISSUE THREAD

**Issue by celsomtrindade** [alexcrack/angular-ui-notification#107]
When migrating to AngularJs 1.6 this error appears:

> Possibly unhandled rejection: {}

Using the same files but with Angular 1.5.8/.9 works fine, just when migrating to 1.6 this error appears. Any ideas?

**Comment by lakylekidd** [comment]
Same issue here. Do you guys have any solution for this?

**Comment by prondzyn** [comment]
Issue cased because `success` function was removed from Angular 1.6. Related to #106.  PR #102 for this is hanging out :(

**Comment by celsomtrindade** [comment]
Eventought the `succes -> then` can solve the main problem, from time to time I still get this error, but I don't know it may be causing it.

**Comment by prondzyn** [comment]
You can follow this instruction: 

https://coderwall.com/p/q_gh-w/fork-and-patch-npm-moduels-hosted-on-github 

and use tag from my repo:

https://github.com/prondzyn/angular-ui-notification/tree/for_ng_1.6

Tested.

**Comment by agustinramos** [comment]
@prondzyn nice!

**Comment by alexcrack** [comment]
Fixed
