### ISSUE TITLE
Handle dupplicates

### ISSUE THREAD

**Issue by nicgirault** [alexcrack/angular-ui-notification#12]
Hello! I would like to add an option to display a notification only if its not already displayed. Would you like me to write this?

**Comment by Fonger** [comment]
I think this shouldn't be included in angular-ui-notification.

You can just write a small notification model and record what notifications have been shown to determine if you need to call angular-ui-notification.

For instance
```js
var shownIDs = [];
function displayNotification (id, message) {
  for(var i = 0; i < shownIDs.length; i++) {
    if(shownIDs[i]===id)
      return;
  }
  Notification.success(message);
  shownIDs.push(id);
}
```

**Comment by alexcrack** [comment]
I'm working on adding the configuration service for notifications. 
Yes, you may write this functional and make pull-request.
It might be I add option for enabling/disabling this functionanal at the future configuration service.

**Comment by alexcrack** [comment]
Now you can provide replaceMessage when showing the notification. It replacese all showed messages by a new message

```javascript
Notification.info({
    message: "Info message (replace messages)",
    replaceMessage: true
});
```
Also you can configure the default option value by the provider NotificationProvider. I'll update documentation for it soon.

**Comment by alexcrack** [comment]
Option replaceMessage in v0.0.10
