### ISSUE TITLE
feature request. Center notifications

### ISSUE THREAD

**Issue by amit777** [alexcrack/angular-ui-notification#28]
Could we have notifications optionally centered at the top or bottom of the screen (as opposed to the existing left, and right options).  Also, could the text within the notification be centered by default.  Basically looking something like google apps notification that show up at the top center.

Thanks for the really useful module!

**Comment by alexcrack** [comment]
I'm planning to realize it.

**Comment by bhaskerchari** [comment]
Hi @alexcrack,

First of all really thanks for the amazing stuff with the notifications service. Its really cool, btw did you get a chance to work on this feature request of positioning the notification center from top or bottom which will be more appropriate as per our application design.

Please let us know if this is in your TODO list or anywhere near or sooner in further releases.

Thanks,
Bhasker

**Comment by alexcrack** [comment]
Yes. It's in my TODO list.

**Comment by alexcrack** [comment]
Added in b7b24e23bf6df73a82e8efbcd365839d6ab109a5
Should work in v0.0.14

**Comment by bhaskerchari** [comment]
Hi @alexcrack much appreciated, thanks for making the changes so fast :+1: I have tested the changes and seems to be working fine :)
