### ISSUE TITLE
Use notification in HttpInterceptor

### ISSUE THREAD

**Issue by lenczykt** [alexcrack/angular-ui-notification#29]
Hi,

I'd like to use Notification in my interceptor. It's seams that i can't because there is circular dependency problem:

```javascript
$http <- Notification <- errorHttpInterceptor <- $http <- $templateRequest <- $compile
```

This is how i'm registering interceptor:

```javascript
angular.module('myModule', [])
  .config(function($httpProvider) {
    $httpProvider.interceptors.push('errorHttpInterceptor');
  });

angular
  .module('myModule')
  .factory('errorHttpInterceptor', function (Notification) {

    return {
      'responseError': handleErrorResponse
    };

    function handleErrorResponse(response) {
        Notification.error('error');
    }

```

Do you have any ideas?

**Comment by alexcrack** [comment]
Yes. I have an idea. Try to use $interceptor manually.
Example:

angular.module('myModule', [])
  .config(function($httpProvider) {
    $httpProvider.interceptors.push('errorHttpInterceptor');
  });

```javascript
angular
  .module('myModule')
  .factory('errorHttpInterceptor', function ($injector) {

    var Notification = $injector.get('Notification');

    return {
      'responseError': handleErrorResponse
    };

    function handleErrorResponse(response) {
        Notification.error('error');
    }
```

**Comment by lenczykt** [comment]
Thank you. It works

**Comment by brenjt** [comment]
I am having this exact same issue. I tried to code above and did not have any success.

    angular.module('ui', [])
        .config(function($httpProvider) {
            $httpProvider.interceptors.push('baseHttpInterceptor');
        })
       .factory('baseHttpInterceptor', function ($injector) {

           var Notification = $injector.get('Notification');

           return {
               'responseError': function() {
                   Notification.error('Oops');
               }
           };
        });

Circular dependency error:

    Circular dependency found: 
    $compile <- Notification <- baseHttpInterceptor <- $http <- $templateRequest <- $compile

Any ideas?
