### ISSUE TITLE
startRight on call

### ISSUE THREAD

**Issue by SylvainVISSIERE-GUERINET** [alexcrack/angular-ui-notification#30]
It seems that the option startRight is ignored when used as so:

```
Notification.success({message : "txt", startRight: 100});
```

According to the doc: 
"Options can be passed to configuration provider globally or used in the current message."

i don't know if it's a bug or documentation error, i let you see :)

**Comment by alexcrack** [comment]
There is error in documentation.
startRight option works only when you configure service. Documentation will be fixed.
I'm not planning to add this option to message invoking.
Sorry.
