### ISSUE TITLE
Notification.clearAll() not working on IE11

### ISSUE THREAD

**Issue by adallow** [alexcrack/angular-ui-notification#31]
Hi Alex, great library. Unfortunately the Notification.clearAll() function is not working in IE 11.

it think this is becuase you are using element.remove() which is a helper method that is a part of DOM 4 and not supported in IE11.

You can easily resolve this by changing your element.remove to be:
element.parentNode.removeChild(element)

This is just what the DOm 4 helper does. I think this is hopefully an easy 'fix' that will make your great library more cross browser compatible.

thanks,
Albert

**Comment by alexcrack** [comment]
I don't have any machine with Windows and IE.
Please try new version 0.0.14

**Comment by alexcrack** [comment]
I've checked in IE11 the last version (0.1.0). clearAll works perfectly
