### ISSUE TITLE
How to set custom template URL

### ISSUE THREAD

**Issue by lukeclifton** [alexcrack/angular-ui-notification#33]
Hey there,

By default the service looks for the notification template at '/angular-ui-notification.html'.

How do we go about setting this value in our app with a custom template URL?

Thanks,

Luke

**Comment by alexcrack** [comment]
You can pass custom template
for example
```html
<script type="text/ng-template" id="custom_template.html">
    <div class="ui-notification custom-template">
        <div class="message" ng-bind-html="message"></div>
    </div>
</script>
```

and use it

```javascript
Notification.primary({message: "Just message", template: "custom_template.html"});
```

Also you can pass any template url to template option

**Comment by lukeclifton** [comment]
Ok thanks.

It would be awesome to be able to pass a 'templateUrl' param to the config options. That means you don't have to repeat yourself by adding in the 'template' value every time you write a Notification when using a custom template location.

I've copied the script for now and manually changed the 'uiNotificationTemplates' value but this stops me using the module from bower directly which is a shame.

What do you think?

**Comment by alexcrack** [comment]
I agree. It would be useful.
I will implement it.

**Comment by lukeclifton** [comment]
Awesome! :)

**Comment by dgurkaynak** [comment]
+1 for this request.

**Comment by anonrig** [comment]
+1

**Comment by damjtoh** [comment]
+1

**Comment by alexcrack** [comment]
Added option 'templateUrl' in v0.0.12 (f843c43).
Option can be passed to the configuration provider and also to Notification's methods.
See examples in ./demo directory.

Attention
Value-service "uiNotificationTemplates" has been deleted!
