### ISSUE TITLE
Config error

### ISSUE THREAD

**Issue by fahussain** [alexcrack/angular-ui-notification#38]
I am trying to do global configuration and running into errors. Here is a forked plunker.

http://plnkr.co/edit/HRTVD29hJVr74E1OFlma?p=preview

Am I doing something wrong?

**Comment by alexcrack** [comment]
The plunker demo is out of date.
You may update it according to documentation using new version of library (also you may use files from 'demo' directory).

**Comment by alexcrack** [comment]
Updated plunker demo
fixed by 9718092
