### ISSUE TITLE
position parameters not working

### ISSUE THREAD

**Issue by fahussain** [alexcrack/angular-ui-notification#39]
Here is a forked plunker with the issue.

http://plnkr.co/edit/OtaIim7rhuvCpd1ypITB?p=preview

**Comment by alexcrack** [comment]
The plunker demo is out of date.
You may update it according to documentation using new version of library (also you may use files from 'demo' directory).

**Comment by alexcrack** [comment]
Updated plunker demo
fixed by 9718092
