### ISSUE TITLE
How to use ui-notification in combination with a exception handler?

### ISSUE THREAD

**Issue by julmot** [alexcrack/angular-ui-notification#42]
Hello,

I would like to use angular-ui-notification inside a exceptionHandler like here:
http://stackoverflow.com/a/16942964/3894981
Instead of ``alert(...)`` I would like to use ``Notification.error(...)``.
However this causes an error:
https://docs.angularjs.org/error/$injector/cdep?p0=$rootScope%20%3C-%20$timeout%20%3C-%20Notification%20%3C-%20$exceptionHandler%20%3C-%20$rootScope%20%3C-%20$translate
What is the workaround to use this extension to show error messages to the user?

**Comment by alexcrack** [comment]
Please, look up for these isues: #32, #29
