### ISSUE TITLE
Destroy associated scope when template element is removed

### ISSUE THREAD

**Issue by Yuyuu** [alexcrack/angular-ui-notification#43]
I might be missing something but it seems that the scope created for each notification (`var scope = args.scope.$new();`) is never destroyed.

Is there a way to properly cleanup the scope when the template element is removed ?

**Comment by alexcrack** [comment]
Just tested it. Yes you are right.
Many of created scopes will influence on perfomance.
It will be fixed in future. Thank you.

**Comment by cklemming** [comment]
Any update on this? Thanks for a great library otherwise.

**Comment by dgreene1** [comment]
Glad someone caught that. Any idea when the fix/enhancement will be available?

**Comment by alexcrack** [comment]
Fixed in 2e17ab143dd9e1dc02aa6a2ec9532e97c62f6e47

New release coming soon
