### ISSUE TITLE
Use explicit dependency injection for the provider in the source file

### ISSUE THREAD

**Issue by Yuyuu** [alexcrack/angular-ui-notification#44]
The fact that explicit dependency injection is not used for the provider in the source file is causing problems when using browserify & ng-annotate, which is blocking.

It requires the provider to be created with:
```javascript
this.$get = ['$timeout', '$http', '$compile', '$templateCache', '$rootScope', '$injector', '$sce', '$q', '$window',
        function($timeout, $http, $compile, $templateCache, $rootScope, $injector, $sce, $q, $window) {
              ...
        }
]
```

It is done in your minified file but the source file is used with browserify.

**Comment by Yuyuu** [comment]
After looking at the other packages I use, the recommended strategy is to release two different files for your package. A minified version (as it is already the case) but also un unminified version. This is what is done with all the other packages I can see.

I managed to make it work by adding a gulp task:

```javascript
gulp.src(['src/*.js'])
      .pipe(jshint())
      .pipe(jshint.reporter('default'))
      .pipe(jshint.reporter('fail'))
      .pipe(ngAnnotate())
      .pipe(addsrc('build/*.js'))
      .pipe(order([
          'src/*.js',
          'build/angular-ui-notification.templates.js'
      ]))
      .pipe(concat('angular-ui-notification.js'))
      .pipe(header(banner, { pkg : pkg }))
      .pipe(gulp.dest('dist'));
});
```

I just removed the minification and demo destination instructions but maybe you can come up with something better as I don't know my way around gulp that much.

Sorry for being a bit needy but this is preventing me from releasing to production so if you could have a look at it in the near future it would be great.

**Comment by Yuyuu** [comment]
Actually, this can be done just by adding two lines to the service task before uglification.

```javascript
gulp.task('service', function() {
    gulp.src(['src/*.js'])
        .pipe(jshint())
        .pipe(jshint.reporter('default'))
        .pipe(jshint.reporter('fail'))
        .pipe(ngAnnotate())
        .pipe(addsrc('build/*.js'))
        .pipe(order([
            'src/*.js',
            'build/angular-ui-notification.templates.js'
        ]))
        .pipe(concat('angular-ui-notification.js'))

        .pipe(header(banner, { pkg : pkg }))
        .pipe(gulp.dest('dist'))

        .pipe(uglify())
        .pipe(rename({
            suffix: '.min'
        }))
        .pipe(header(banner, { pkg : pkg }))
        .pipe(gulp.dest('dist'))
        .pipe(gulp.dest('demo'));
});
```

**Comment by alexcrack** [comment]
Merged
