### ISSUE TITLE
custom template

### ISSUE THREAD

**Issue by HoplaGeiss** [alexcrack/angular-ui-notification#46]
Can you help me find out why custom template doesn't work ?

I am calling the service this way
`Notification({message: 'Hello', delay: 10000, templateUrl: 'main/notification-template.html'})`

My html file is in the templates folder.
A notification appears, but with the default template.

**Comment by karthilxg** [comment]
@HoplaGeiss Check your version, custom template issue is fixed in the latest.

https://github.com/alexcrack/angular-ui-notification/commit/52fbe2f170868ae250dc5073146887f1e5e4f549

**Comment by HoplaGeiss** [comment]
Hehe, indeed!
I never think about checking versions :/
Thanks!

**Comment by karthilxg** [comment]
@HoplaGeiss You're welcome.
