### ISSUE TITLE
disable close feature

### ISSUE THREAD

**Issue by HoplaGeiss** [alexcrack/angular-ui-notification#47]
I don't want the notifications to disappear when the user clicks on it.
Would it be possible to put this in options ?

**Comment by alexcrack** [comment]
Yes.
It's easy to implement.
I'll do it shortly.
Thanks for an idea.

**Comment by twolff-iow** [comment]
+1

Would be nice to have this option as a global and custom option per message.

**Comment by BabysbreathJJ** [comment]
Same problem here. I annotate the code of click function of the notification, but I don't know how to close a notification using a click event in the message.

**Comment by paulosborne** [comment]
+1

This would be really useful, and I believe there is a merge request open for it ;)

**Comment by alexcrack** [comment]
Added by b2e4d7261e31dd1a9414e07614906d43dfdb8fb1
