### ISSUE TITLE
NPM package?

### ISSUE THREAD

**Issue by twolff-iow** [alexcrack/angular-ui-notification#50]
Hi,

first of all, thanks for the nice package. It is exactly what I was looking for. Would it be possible to also provide this as an npm package? I am not using bower right now and it would be convenient to have this on the global npm registry as well. Meanwhile I have pushed it to a private npm repo which works for now.

Tobias.

**Comment by szkrd** [comment]
Yes, an npm package would be really nice!

**Comment by alexcrack** [comment]
Version 0.1.0 published.
