### ISSUE TITLE
Feature request: click handler

### ISSUE THREAD

**Issue by nstohler** [alexcrack/angular-ui-notification#52]
Our use case calls for a notification item that can be clicked on and then would call a function in our code (to show more details about the item using ngDialog). I tried adding ng-click handlers in the template, but the code never got called. It would be great if we could pass in some arguments in some way of course!

**Comment by Valkendorm** [comment]
+1 for this

However, I actually just did a test by using [angular-bind-html-compile](https://github.com/incuna/angular-bind-html-compile) and customized the default template with this directive and it worked.

**Comment by shashvattrip** [comment]
+1 on this. Would definitely be very helpful.

**Comment by mechdrew** [comment]
This is already possible without any modification, but it requires a new scope to be added to the notification. [I made a plunk to demonstrate](http://plnkr.co/edit/332Y5TRcqElWk5RQT7Y2) how this can be accomplished; the scope can either be created as in the example, or using $rootScope if necessary.

**Comment by alexcrack** [comment]
Added by 7e2fc4ffda24f5150700bbd7a88fa1846631d9f2
