### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by raistlin** [alexcrack/angular-ui-notification#58]
On Tag 0.0.14 version specified on bower.json is mismatched. It says 0.0.12 instead on 0.0.14. Because of this fact, this error is generated:

`*** [err :: xxxx.com] bower angular-ui-notification#~0.0.14   mismatch Version declared in the json (0.0.12) is different than the resolved one (0.0.14)`

**Comment by alexcrack** [comment]
Updated
