### ISSUE TITLE
Problems in instalation with Bower

### ISSUE THREAD

**Issue by jeanrl** [alexcrack/angular-ui-notification#59]
I run:

bower install angular-ui-notification --save

And I get the following bower messages:

bower not-cached    git://github.com/alexcrack/angular-ui-notification.git#*
bower resolve       git://github.com/alexcrack/angular-ui-notification.git#*
bower download      https://github.com/alexcrack/angular-ui-notification/archive/v0.0.14.tar.gz
bower extract       angular-ui-notification#* archive.tar.gz
bower mismatch      Version declared in the json (0.0.12) is different than the resolved one (0.0.14)
bower resolved      git://github.com/alexcrack/angular-ui-notification.git#0.0.14
bower install       angular-ui-notification#0.0.14
bower no-json       No bower.json file to save to, use bower init to create one

And the dist folder is empty.

How to solve this problem?

The version of my Bower is 1.6.3.

Grateful.

**Comment by gugahoi** [comment]
It seems to me you are missing your own `bower.json` file. You need to do a `bower init` command before you start using it.

**Comment by alexcrack** [comment]
I've tested. All is Ok.

```
$ mkdir test_notification
$ cd test_notification/
$ bower install angular-ui-notification --save
bower angular-ui-notification#* cached git://github.com/alexcrack/angular-ui-notification.git#0.0.14
bower angular-ui-notification#*         validate 0.0.14 against git://github.com/alexcrack/angular-ui-notification.git#*
bower angular-ui-notification#~0.0.14    install angular-ui-notification#0.0.14
bower                                    no-json No bower.json file to save to, use bower init to create one

angular-ui-notification#0.0.14 bower_components/angular-ui-notification

```

To fix the last message you should follow the solution above by gugahoi.
