### ISSUE TITLE
No Delay is not working

### ISSUE THREAD

**Issue by Janjuks** [alexcrack/angular-ui-notification#60]
For `delay` option description Readme says: `Number of ms before notification fades out. If not an integer, notification will persist until killed.` I tried setting it to non numerical value both, for a single message and in global options, but the message dissapears immediately. See plunker: http://plnkr.co/edit/4WKNdPOieAOzFJLQbOju?p=preview

**Comment by joshuaja** [comment]
I set delay: null and it seems to be working

**Comment by Janjuks** [comment]
Can you post a plunker? I tried with null on chrome, ff, ie, opera and on all of these the message disappears instantly. On ff it doesn't even come up.

**Comment by Mic75** [comment]
Hi @Janjuks,

In you plunker, I replaced the angular-ui-notification js file, with the latest (0.1.0) from the repo and the "no delay" is working.

**Comment by alexcrack** [comment]
Works with latest version 0.1.0
