### ISSUE TITLE
option 'type' don't work.

### ISSUE THREAD

**Issue by tomerof** [alexcrack/angular-ui-notification#64]
I'm trying to fire notifications with the parameter: type
like this:
var messages = [];
messages.push({type:'error',content:'Error notification'});
messages.push({type:'info',content:'Info notification'});
messages.push({type:'primary',content:'Primary notification'});
messages.push({type:'success',content:'Success notification'});

angular.forEach(messages,function(message,key){
    Notification({title:'test',type:message.type,message:message.content});
});

**Comment by mechdrew** [comment]
I've fixed this in #41.

**Comment by alexcrack** [comment]
Merged
