### ISSUE TITLE
CSS prevents from moving notification to bottom

### ISSUE THREAD

**Issue by fulup-bzh** [alexcrack/angular-ui-notification#7]
First thank you for sharing your work. I really appreciate your coding. It is clean and easy to understand.

Bug/Feature: In your CSS you force "top" definition to '-100px' which prevents moving notification to bottom of the page. Moving to bottom while not available in config option is easy. You only have to replace "top" by "bottom" in line 58 of your script
```
element.css('bottom', top + 'px');
element.css('right', right + 'px');
```
Note: I do not use LESS but SCSS, I placed https://gist.github.com/fulup-bzh/d3fe7a5e537bc5a46e3d a SCSS version of your LESS file. It is exactly the same expect that I remove dependencies to BootStrap [I'm using F5].

Request: would be nice to have an option to place notification at bottom of the page without hacking your javascript.

**Comment by ArtworkAD** [comment]
:+1: exactly. Would like to see an offset option as well.

**Comment by thiagoalvernaz** [comment]
#20

**Comment by alexcrack** [comment]
#21
