### ISSUE TITLE
On iOS, positionX: 'center' doesn't work correctly.

### ISSUE THREAD

**Issue by jmwohl** [alexcrack/angular-ui-notification#73]
The notification starts all the way left and transitions to the correct final center position rather than starting there.

**Comment by Cody-Nicholson** [comment]
Safari on mac OSX has the same issue.

As far as I can tell Safari is implying that the starting position for a fixed element is 0px for transitions, even if css has not specifically defined it at 0px.

**Comment by Cody-Nicholson** [comment]
Just submitted https://github.com/alexcrack/angular-ui-notification/pull/76.  Which should also fix iOS Safari as well.

**Comment by alexcrack** [comment]
Fixed by 8ce8ecfd60dd527282dacfb3e069b04afe43d0f4

**Comment by jmwohl** [comment]
Great, thanks! Can we expect a new release in NPM soon too?

**Comment by alexcrack** [comment]
Yes.
