### ISSUE TITLE
Notification affecting CacheFactory

### ISSUE THREAD

**Issue by andela-omesanni** [alexcrack/angular-ui-notification#93]
I am making use of CacheFactory and angular-ui-notification in a project i am working on. Now anytime I inject the Notification service in my http interceptor I get this error below:
`Uncaught Error: [$cacheFactory:iid] CacheId '$http' is already taken`

Please can you tell me how I can fix this error caused by the Notification service as I noticed that the $http request inside the $get function of the NotificationProvider makes use of $templateCache.

Thanks for your anticipated assistance

**Comment by wujitouch** [comment]
Change the name of the cache used by the $http service. See here:

https://github.com/jmdobry/angular-cache#using-angular-cache-with-http
