### ISSUE TITLE
notification inside a container

### ISSUE THREAD

**Issue by theraaz** [alexcrack/angular-ui-notification#94]
by default notification is added inside `body`, is it possible to show notification inside a container?
In my case, I don't want to show that over the sidebar and/or header

**Comment by alexcrack** [comment]
It will be soon after merging #77

**Comment by theraaz** [comment]
That will be great. Hope it'll be merged soon

**Comment by EAziied** [comment]
+1

**Comment by alexcrack** [comment]
Added by d53dc85cfee9bf3b48b3a1b88a521a72f6a0023c

**Comment by theraaz** [comment]
not available in bower yet
![image](https://cloud.githubusercontent.com/assets/7224736/18162961/8ec819f2-7030-11e6-9149-85eb8571b488.png)
